#! /usr/bin/env ruby

require_relative 'env.rb'
require 'octokit'
require 'pry'

unless defined? PAT && defined? USER
  raise StandardError, 'Personal Access Token and User variables must be definied. Please refer to README.md'
end

client = Octokit::Client.new(access_token: PAT)

prs = client.search_issues("is:open is:pr author:#{USER} archived:false")

until prs.items[0].nil?

  prs.items.each do |pr|
    if pr.repository_url[29..45] == 'learn-co-students'
      puts 'closing: ' + pr.repository_url[29..-1]
      client.close_issue(pr.repository_url[29..-1], pr.number)
    end 
  end

  prs = client.search_issues("is:open is:pr author:#{USER} archived:false")

end

puts 'learn-co PR closing for this user complete!'
puts
puts 'do you want to delete this repo? y/n'
response = gets.chomp.strip

if response.downcase == 'y'
  puts 'deleting this repo... (including your Personal Access Token)'

  system("pwd | tail -c 17 | read tmp ; [ $tmp = 'learn_co_cleaner' ] && rm -rf $dir ")
else  
  puts 'ok, be sure to delete your Personal Access Token! When you done!'
end